       PROCESS DLL,NODYNAM,TEST(NOSEP),NOCICS,PGMN(LU)
      *+---------------------------------------------------------------+
      *| DFHEI1                                                        |
      *|     This is STUB program generated by the IBM z/OS Automated  |
      *|     Unit Testing Framework (zUnit)                            |
      *|     For DFHEI1 call of CICS command                           |
      *| Date Generated: 02/07/2019 06:32                              |
      *+---------------------------------------------------------------+
       IDENTIFICATION DIVISION.
       PROGRAM-ID. DFHEI1.
       DATA DIVISION.
       WORKING-STORAGE SECTION.
       1 FAIL-MESSAGE-TXT PIC X(254) VALUE "HELLO FROM DFHEI1".
       1 FAIL-MESSAGE-LEN PIC S9(9) COMP-5 VALUE 19.
       1 AZ-TEST-NAME-FOR-SUB   PIC X(254) EXTERNAL.
       1 AZ-TEST-NAME-LEN  PIC S9(9) COMP-5 EXTERNAL.
       1 AZ-TEST-CASE-PTR  POINTER EXTERNAL.
       1 AZ-RECORD.
         3 AZ-RECORD-COUNT OCCURS 4 PIC 9(5) COMP-5 VALUE 0.
       1 AZ-LAST-TEST-NAME   PIC X(254) VALUE SPACES.
       1 AZ-LAST-TEST-NAME-LEN  PIC S9(9) COMP-5 VALUE 0.
       1 AZ-COMPARE EXTERNAL.
         3 AZ-COMPARE-ITEM-NAME-PTR POINTER.
         3 AZ-COMPARE-ITEM-NAME-LEN PIC S9(9) COMP-5.
         3 AZ-COMPARE-ITEM-VALUE-PTR POINTER.
         3 AZ-COMPARE-ITEM-VALUE-LEN PIC S9(9) COMP-5.
         3 AZ-COMPARE-ITEM-EXP-VALUE-PTR POINTER.
         3 AZ-COMPARE-ITEM-EXP-VALUE-LEN PIC S9(9) COMP-5.
       1 AZ-TEST-EXPECTED-DATA-VALUE.
          3 ZUT00000000.
            5 PIC X(8) DISPLAY VALUE 'LGIPDB01'.
          3 ZUT00000001.
            5 PIC X(6) DISPLAY VALUE '01IMOT'.
          3 ZUT00000002.
            5 PIC X(10) DISPLAY VALUE '          '.
          3 ZUT00000003.
            5 PIC X(10) DISPLAY VALUE '          '.
          3 ZUT00000004.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(6) DISPLAY VALUE '      '.
          3 ZUT00000005.
            5 PIC X(10) VALUE X'40404040404040404040'.
          3 ZUT00000006.
            5 PIC X(10) DISPLAY VALUE '          '.
          3 ZUT00000007.
            5 PIC X(6) VALUE X'404040404040'.
          3 ZUT00000008.
            5 PIC X(15) DISPLAY VALUE '               '.
          3 ZUT00000009.
            5 PIC X(15) DISPLAY VALUE '               '.
          3 ZUT0000000A.
            5 PIC X(6) VALUE X'404040404040'.
          3 ZUT0000000B.
            5 PIC X(7) DISPLAY VALUE '       '.
          3 ZUT0000000C.
            5 PIC X(8) DISPLAY VALUE '        '.
          3 ZUT0000000D.
            5 PIC X(4) VALUE X'40404040'.
          3 ZUT0000000E.
            5 PIC X(10) DISPLAY VALUE '          '.
          3 ZUT0000000F.
            5 PIC X(6) VALUE X'404040404040'.
          3 ZUT00000010.
            5 PIC X(6) VALUE X'404040404040'.
          3 ZUT00000011.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(14) DISPLAY VALUE '              '.
            5 PIC X(27549) DISPLAY VALUE SPACES.
       1 AZ-TEST-INPUT-DATA-VALUE.
          3 ZUT00000012.
            5 PIC X(6) DISPLAY VALUE '01IMOT'.
          3 ZUT00000013.
            5 PIC X(10) DISPLAY VALUE '2011-05-11'.
          3 ZUT00000014.
            5 PIC X(10) DISPLAY VALUE '2012-05-10'.
          3 ZUT00000015.
            5 PIC X(20) DISPLAY VALUE '2011-05-11-17.12.17.'.
            5 PIC X(6) DISPLAY VALUE '000000'.
          3 ZUT00000016.
            5 PIC X(10) DISPLAY VALUE '          '.
          3 ZUT00000017.
            5 PIC X(15) DISPLAY VALUE 'FORD           '.
          3 ZUT00000018.
            5 PIC X(15) DISPLAY VALUE 'KA             '.
          3 ZUT00000019.
            5 PIC X(7) DISPLAY VALUE 'LL60LOO'.
          3 ZUT0000001A.
            5 PIC X(8) DISPLAY VALUE 'ORANGE  '.
          3 ZUT0000001B.
            5 PIC X(10) DISPLAY VALUE '1999-07-19'.
          3 ZUT0000001C.
            5 PIC X(20) DISPLAY VALUE 'FINAL               '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(20) DISPLAY VALUE '                    '.
            5 PIC X(14) DISPLAY VALUE '              '.
            5 PIC X(27549) DISPLAY VALUE SPACES.
          3 ZUT0000001D.
            5 PIC X(4) DISPLAY VALUE 'SSP1'.
          3 ZUT0000001E.
            5 PIC X(4) DISPLAY VALUE '0024'.
          3 ZUT0000001F.
            5 PIC X(1) DISPLAY VALUE
            ''''.
          3 ZUT00000020.
            5 PIC X(2) VALUE X'0E08'.
          3 ZUT00000021.
            5 PIC X(8) DISPLAY VALUE '        '.
       1 DFHEIBLK IS EXTERNAL.
         2 EIBTIME PICTURE S9(7) USAGE COMPUTATIONAL-3.
         2 EIBDATE PICTURE S9(7) USAGE COMPUTATIONAL-3.
         2 EIBTRNID PICTURE X(4).
         2 EIBTASKN PICTURE S9(7) USAGE COMPUTATIONAL-3.
         2 EIBTRMID PICTURE X(4).
         2 DFHEIGDI PICTURE S9(4) USAGE COMPUTATIONAL-5.
         2 EIBCPOSN PICTURE S9(4) USAGE COMPUTATIONAL-5.
         2 EIBCALEN PICTURE S9(4) USAGE COMPUTATIONAL-5.
         2 EIBAID PICTURE X(1).
         2 EIBFN PICTURE X(2).
          2 EIBFN-AZ REDEFINES EIBFN.
          3 PIC X(2) DISPLAY.
         2 EIBRCODE PICTURE X(6).
         2 EIBDS PICTURE X(8).
         2 EIBREQID PICTURE X(8).
         2 EIBRSRCE PICTURE X(8).
         2 EIBSYNC PICTURE X.
         2 EIBFREE PICTURE X.
         2 EIBRECV PICTURE X.
         2 EIBSEND PICTURE X.
         2 EIBATT PICTURE X.
         2 EIBEOC PICTURE X.
         2 EIBFMH PICTURE X.
         2 EIBCOMPL PICTURE X(1).
         2 EIBSIG PICTURE X(1).
         2 EIBCONF PICTURE X(1).
         2 EIBERR PICTURE X(1).
         2 EIBERRCD PICTURE X(4).
         2 EIBSYNRB PICTURE X.
         2 EIBNODAT PICTURE X.
         2 EIBRESP PICTURE S9(8) USAGE COMPUTATIONAL.
         2 EIBRESP2 PICTURE S9(8) USAGE COMPUTATIONAL.
         2 EIBRLDBK PICTURE X(1).
       LOCAL-STORAGE SECTION.
       1 AZ-COMPARE-ITEM-NAMES.
         3 ZUT00000022.
            5 PIC X(20) DISPLAY VALUE 'CA-REQUEST-ID OF DFH'.
            5 PIC X(8) DISPLAY VALUE 'COMMAREA'.
         3 ZUT00000024.
            5 PIC X(20) DISPLAY VALUE 'CA-RETURN-CODE OF DF'.
            5 PIC X(9) DISPLAY VALUE 'HCOMMAREA'.
         3 ZUT00000026.
            5 PIC X(20) DISPLAY VALUE 'CA-CUSTOMER-NUM OF D'.
            5 PIC X(10) DISPLAY VALUE 'FHCOMMAREA'.
         3 ZUT00000028.
            5 PIC X(20) DISPLAY VALUE 'CA-POLICY-NUM OF CA-'.
            5 PIC X(20) DISPLAY VALUE 'POLICY-REQUEST OF DF'.
            5 PIC X(9) DISPLAY VALUE 'HCOMMAREA'.
         3 ZUT0000002A.
            5 PIC X(20) DISPLAY VALUE 'CA-ISSUE-DATE OF CA-'.
            5 PIC X(20) DISPLAY VALUE 'POLICY-COMMON OF CA-'.
            5 PIC X(20) DISPLAY VALUE 'POLICY-REQUEST OF DF'.
            5 PIC X(9) DISPLAY VALUE 'HCOMMAREA'.
         3 ZUT0000002C.
            5 PIC X(20) DISPLAY VALUE 'CA-EXPIRY-DATE OF CA'.
            5 PIC X(20) DISPLAY VALUE '-POLICY-COMMON OF CA'.
            5 PIC X(20) DISPLAY VALUE '-POLICY-REQUEST OF D'.
            5 PIC X(10) DISPLAY VALUE 'FHCOMMAREA'.
         3 ZUT0000002E.
            5 PIC X(20) DISPLAY VALUE 'CA-LASTCHANGED OF CA'.
            5 PIC X(20) DISPLAY VALUE '-POLICY-COMMON OF CA'.
            5 PIC X(20) DISPLAY VALUE '-POLICY-REQUEST OF D'.
            5 PIC X(10) DISPLAY VALUE 'FHCOMMAREA'.
         3 ZUT00000030.
            5 PIC X(20) DISPLAY VALUE 'CA-BROKERID OF CA-PO'.
            5 PIC X(20) DISPLAY VALUE 'LICY-COMMON OF CA-PO'.
            5 PIC X(20) DISPLAY VALUE 'LICY-REQUEST OF DFHC'.
            5 PIC X(7) DISPLAY VALUE 'OMMAREA'.
         3 ZUT00000032.
            5 PIC X(20) DISPLAY VALUE 'CA-BROKERSREF OF CA-'.
            5 PIC X(20) DISPLAY VALUE 'POLICY-COMMON OF CA-'.
            5 PIC X(20) DISPLAY VALUE 'POLICY-REQUEST OF DF'.
            5 PIC X(9) DISPLAY VALUE 'HCOMMAREA'.
         3 ZUT00000034.
            5 PIC X(20) DISPLAY VALUE 'CA-PAYMENT OF CA-POL'.
            5 PIC X(20) DISPLAY VALUE 'ICY-COMMON OF CA-POL'.
            5 PIC X(20) DISPLAY VALUE 'ICY-REQUEST OF DFHCO'.
            5 PIC X(6) DISPLAY VALUE 'MMAREA'.
         3 ZUT00000036.
            5 PIC X(20) DISPLAY VALUE 'CA-M-MAKE OF CA-MOTO'.
            5 PIC X(20) DISPLAY VALUE 'R OF CA-POLICY-REQUE'.
            5 PIC X(17) DISPLAY VALUE 'ST OF DFHCOMMAREA'.
         3 ZUT00000038.
            5 PIC X(20) DISPLAY VALUE 'CA-M-MODEL OF CA-MOT'.
            5 PIC X(20) DISPLAY VALUE 'OR OF CA-POLICY-REQU'.
            5 PIC X(18) DISPLAY VALUE 'EST OF DFHCOMMAREA'.
         3 ZUT0000003A.
            5 PIC X(20) DISPLAY VALUE 'CA-M-VALUE OF CA-MOT'.
            5 PIC X(20) DISPLAY VALUE 'OR OF CA-POLICY-REQU'.
            5 PIC X(18) DISPLAY VALUE 'EST OF DFHCOMMAREA'.
         3 ZUT0000003C.
            5 PIC X(20) DISPLAY VALUE 'CA-M-REGNUMBER OF CA'.
            5 PIC X(20) DISPLAY VALUE '-MOTOR OF CA-POLICY-'.
            5 PIC X(20) DISPLAY VALUE 'REQUEST OF DFHCOMMAR'.
            5 PIC X(2) DISPLAY VALUE 'EA'.
         3 ZUT0000003E.
            5 PIC X(20) DISPLAY VALUE 'CA-M-COLOUR OF CA-MO'.
            5 PIC X(20) DISPLAY VALUE 'TOR OF CA-POLICY-REQ'.
            5 PIC X(19) DISPLAY VALUE 'UEST OF DFHCOMMAREA'.
         3 ZUT00000040.
            5 PIC X(20) DISPLAY VALUE 'CA-M-CC OF CA-MOTOR '.
            5 PIC X(20) DISPLAY VALUE 'OF CA-POLICY-REQUEST'.
            5 PIC X(15) DISPLAY VALUE ' OF DFHCOMMAREA'.
         3 ZUT00000042.
            5 PIC X(20) DISPLAY VALUE 'CA-M-MANUFACTURED OF'.
            5 PIC X(20) DISPLAY VALUE ' CA-MOTOR OF CA-POLI'.
            5 PIC X(20) DISPLAY VALUE 'CY-REQUEST OF DFHCOM'.
            5 PIC X(5) DISPLAY VALUE 'MAREA'.
         3 ZUT00000044.
            5 PIC X(20) DISPLAY VALUE 'CA-M-PREMIUM OF CA-M'.
            5 PIC X(20) DISPLAY VALUE 'OTOR OF CA-POLICY-RE'.
            5 PIC X(20) DISPLAY VALUE 'QUEST OF DFHCOMMAREA'.
         3 ZUT00000046.
            5 PIC X(20) DISPLAY VALUE 'CA-M-ACCIDENTS OF CA'.
            5 PIC X(20) DISPLAY VALUE '-MOTOR OF CA-POLICY-'.
            5 PIC X(20) DISPLAY VALUE 'REQUEST OF DFHCOMMAR'.
            5 PIC X(2) DISPLAY VALUE 'EA'.
         3 ZUT00000048.
            5 PIC X(20) DISPLAY VALUE 'CA-M-FILLER OF CA-MO'.
            5 PIC X(20) DISPLAY VALUE 'TOR OF CA-POLICY-REQ'.
            5 PIC X(19) DISPLAY VALUE 'UEST OF DFHCOMMAREA'.
         3 ZUT0000004A.
            5 PIC X(8) DISPLAY VALUE 'LGIPDB01'.
       1 AZ-COMPARE-WORK-ITEMS.
          3 ZUT00000023 PIC X(6) OCCURS 2.
          3 ZUT00000025 PIC 9(2) OCCURS 2.
          3 ZUT00000027 PIC 9(10) OCCURS 2.
          3 ZUT00000029 PIC 9(10) OCCURS 2.
          3 ZUT0000002B PIC X(10) OCCURS 2.
          3 ZUT0000002D PIC X(10) OCCURS 2.
          3 ZUT0000002F PIC X(26) OCCURS 2.
          3 ZUT00000031 PIC X(20) OCCURS 2.
          3 ZUT00000033 PIC X(10) OCCURS 2.
          3 ZUT00000035 PIC X(12) OCCURS 2.
          3 ZUT00000037 PIC X(15) OCCURS 2.
          3 ZUT00000039 PIC X(15) OCCURS 2.
          3 ZUT0000003B PIC X(12) OCCURS 2.
          3 ZUT0000003D PIC X(7) OCCURS 2.
          3 ZUT0000003F PIC X(8) OCCURS 2.
          3 ZUT00000041 PIC X(8) OCCURS 2.
          3 ZUT00000043 PIC X(10) OCCURS 2.
          3 ZUT00000045 PIC X(12) OCCURS 2.
          3 ZUT00000047 PIC X(12) OCCURS 2.
          3 ZUT00000049 PIC X(32323) OCCURS 2.
          3 ZUT0000004B PIC X(8) OCCURS 2.
       1 AZ-CONVERT.
         3 AZ-CONVERT-HEXIN  PIC X(1).
         3 AZ-CONVERT-HEXVAL PIC X(2).
         3 AZ-HEXSTR PIC X(16) VALUE "0123456789ABCDEF".
         3 AZ-DEC  PIC S9(4) COMP VALUE 0.
         3 FILLER REDEFINES AZ-DEC.
           5 FILLER PIC X.
           5 AZ-DECBYTE PIC X.
         3 AZ-I PIC S9(8) COMP.
         3 AZ-J PIC S9(8) COMP.
         3 AZ-Q PIC S9(8) COMP.
         3 AZ-R PIC S9(8) COMP.
         3 AZ-Q1 PIC S9(8) COMP.
         3 AZ-R1 PIC S9(8) COMP.
       LINKAGE SECTION.
       01 ARG0.
         03 ARG0-1  PIC X(2).
         03 ARG0-2  PIC X(8).
         03 ARG0-3A.
            05 ARG0-3A-1  PIC 9(5).
            05 ARG0-3A-2  PIC X(1).
            05 ARG0-3A-3  PIC 9(5).
         03 ARG0-3B REDEFINES ARG0-3A.
            05 ARG0-3B-1  PIC X(4).
            05 ARG0-3B-2  PIC 9(5).
            05 ARG0-3B-3  PIC X(2).
       01 ARG1  POINTER.
       01 ARG2  POINTER.
       01 ARG3  POINTER.
       01 ARG4  POINTER.
       01 ARG5  POINTER.
       01 ARG6  POINTER.
       01 ARG7  POINTER.
       01 ARG8  POINTER.
       01 ARG9  POINTER.
       01 ARG10 POINTER.
       01 ARG11 POINTER.
       01 ARG12 POINTER.
       01 ARG13 POINTER.
       01 ARG14 POINTER.
       01 ARG15 POINTER.
       01 ARG16 POINTER.
       01 ARG17 POINTER.
       01 ARG18 POINTER.
       01 ARG19 POINTER.
       01 ARG20 POINTER.
       01 ARG21 POINTER.
       01 ARG22 POINTER.
       01 ARG23 POINTER.
       01 ARG24 POINTER.
       01 ARG25 POINTER.
       01 ARG26 POINTER.
       01 ARG27 POINTER.
       01 ARG28 POINTER.
       01 ARG29 POINTER.
       01 ARG30 POINTER.
       01 ARG31 POINTER.
       01 ARG32 POINTER.
       01 ARG33 POINTER.
       01 ARG34 POINTER.
       01 ARG35 POINTER.
       01 ARG36 POINTER.
       01 ARG37 POINTER.
       01 ARG38 POINTER.
       01 ARG39 POINTER.
       01 ARG40 POINTER.
       1 LGIPDB01 PIC x(8).
       1 DFHCOMMAREA.
         3 CA-REQUEST-ID PIC X(6).
         3 CA-RETURN-CODE PIC 9(2).
         3 CA-CUSTOMER-NUM PIC 9(10).
         3 CA-REQUEST-SPECIFIC PIC X(32482).
         3 CA-CUSTOMER-REQUEST REDEFINES CA-REQUEST-SPECIFIC.
         5 CA-FIRST-NAME PIC X(10).
         5 CA-LAST-NAME PIC X(20).
         5 CA-DOB PIC X(10).
         5 CA-HOUSE-NAME PIC X(20).
         5 CA-HOUSE-NUM PIC X(4).
         5 CA-POSTCODE PIC X(8).
         5 CA-NUM-POLICIES PIC 9(3).
         5 CA-PHONE-MOBILE PIC X(20).
         5 CA-PHONE-HOME PIC X(20).
         5 CA-EMAIL-ADDRESS PIC X(100).
         5 CA-POLICY-DATA PIC X(32267).
         3 CA-CUSTSECR-REQUEST REDEFINES CA-REQUEST-SPECIFIC.
         5 CA-CUSTSECR-PASS PIC X(32).
         5 CA-CUSTSECR-COUNT PIC X(4).
         5 CA-CUSTSECR-STATE PIC X.
         5 CA-CUSTSECR-DATA PIC X(32445).
         3 CA-POLICY-REQUEST REDEFINES CA-REQUEST-SPECIFIC.
         5 CA-POLICY-NUM PIC 9(10).
         5 CA-POLICY-COMMON.
         7 CA-ISSUE-DATE PIC X(10).
         7 CA-EXPIRY-DATE PIC X(10).
         7 CA-LASTCHANGED PIC X(26).
         7 CA-BROKERID PIC 9(10).
          7 CA-BROKERID-AZ REDEFINES CA-BROKERID.
          8 PIC X(10) DISPLAY.
         7 CA-BROKERSREF PIC X(10).
         7 CA-PAYMENT PIC 9(6).
          7 CA-PAYMENT-AZ REDEFINES CA-PAYMENT.
          8 PIC X(6) DISPLAY.
         5 CA-POLICY-SPECIFIC PIC X(32400).
         5 CA-ENDOWMENT REDEFINES CA-POLICY-SPECIFIC.
         7 CA-E-WITH-PROFITS PIC X.
         7 CA-E-EQUITIES PIC X.
         7 CA-E-MANAGED-FUND PIC X.
         7 CA-E-FUND-NAME PIC X(10).
         7 CA-E-TERM PIC 99.
         7 CA-E-SUM-ASSURED PIC 9(6).
         7 CA-E-LIFE-ASSURED PIC X(31).
         7 CA-E-PADDING-DATA PIC X(32348).
         5 CA-HOUSE REDEFINES CA-POLICY-SPECIFIC.
         7 CA-H-PROPERTY-TYPE PIC X(15).
         7 CA-H-BEDROOMS PIC 9(3).
         7 CA-H-VALUE PIC 9(8).
         7 CA-H-HOUSE-NAME PIC X(20).
         7 CA-H-HOUSE-NUMBER PIC X(4).
         7 CA-H-POSTCODE PIC X(8).
         7 CA-H-FILLER PIC X(32342).
         5 CA-MOTOR REDEFINES CA-POLICY-SPECIFIC.
         7 CA-M-MAKE PIC X(15).
         7 CA-M-MODEL PIC X(15).
         7 CA-M-VALUE PIC 9(6).
          7 CA-M-VALUE-AZ REDEFINES CA-M-VALUE.
          8 PIC X(6) DISPLAY.
         7 CA-M-REGNUMBER PIC X(7).
         7 CA-M-COLOUR PIC X(8).
         7 CA-M-CC PIC 9(4).
          7 CA-M-CC-AZ REDEFINES CA-M-CC.
          8 PIC X(4) DISPLAY.
         7 CA-M-MANUFACTURED PIC X(10).
         7 CA-M-PREMIUM PIC 9(6).
          7 CA-M-PREMIUM-AZ REDEFINES CA-M-PREMIUM.
          8 PIC X(6) DISPLAY.
         7 CA-M-ACCIDENTS PIC 9(6).
          7 CA-M-ACCIDENTS-AZ REDEFINES CA-M-ACCIDENTS.
          8 PIC X(6) DISPLAY.
         7 CA-M-FILLER PIC X(32323).
         5 CA-COMMERCIAL REDEFINES CA-POLICY-SPECIFIC.
         7 CA-B-ADDRESS PIC X(255).
         7 CA-B-POSTCODE PIC X(8).
         7 CA-B-LATITUDE PIC X(11).
         7 CA-B-LONGITUDE PIC X(11).
         7 CA-B-CUSTOMER PIC X(255).
         7 CA-B-PROPTYPE PIC X(255).
         7 CA-B-FIREPERIL PIC 9(4).
         7 CA-B-FIREPREMIUM PIC 9(8).
         7 CA-B-CRIMEPERIL PIC 9(4).
         7 CA-B-CRIMEPREMIUM PIC 9(8).
         7 CA-B-FLOODPERIL PIC 9(4).
         7 CA-B-FLOODPREMIUM PIC 9(8).
         7 CA-B-WEATHERPERIL PIC 9(4).
         7 CA-B-WEATHERPREMIUM PIC 9(8).
         7 CA-B-STATUS PIC 9(4).
         7 CA-B-REJECTREASON PIC X(255).
         7 CA-B-FILLER PIC X(31298).
         5 CA-CLAIM REDEFINES CA-POLICY-SPECIFIC.
         7 CA-C-NUM PIC 9(10).
         7 CA-C-DATE PIC X(10).
         7 CA-C-PAID PIC 9(8).
         7 CA-C-VALUE PIC 9(8).
         7 CA-C-CAUSE PIC X(255).
         7 CA-C-OBSERVATIONS PIC X(255).
         7 CA-C-FILLER PIC X(31854).
      *
       PROCEDURE DIVISION USING ARG0 ARG1 ARG2 ARG3 ARG4 ARG5
           ARG6 ARG7 ARG8 ARG9 ARG10 ARG11 ARG12 ARG13 ARG14 ARG15
           ARG16 ARG17 ARG18 ARG19 ARG20 ARG21 ARG22 ARG23 ARG24 ARG25
           ARG26 ARG27 ARG28 ARG29 ARG30 ARG31 ARG32 ARG33 ARG34 ARG35
           ARG36 ARG37 ARG38 ARG39 ARG40.
      * OUTPUT-START-MESSAGE.
           DISPLAY 'DFHEI1 Started...'
      * EXEC CICS LINK
           IF ARG0-1 = X'0e02'
             DISPLAY 'EXEC CICS LINK'
             DISPLAY 'Statement Number:' ARG0-3A-1
             EVALUATE ARG0-3A-1
             WHEN 0
               CONTINUE
             WHEN 360
               DISPLAY 'EXEC CICS LINK (Statement=360,Line=127)'
               SET ADDRESS OF LGIPDB01 TO ADDRESS OF ARG1
               SET ADDRESS OF DFHCOMMAREA TO ADDRESS OF ARG2
               IF AZ-LAST-TEST-NAME-LEN = AZ-TEST-NAME-LEN AND
                  AZ-LAST-TEST-NAME(1:AZ-TEST-NAME-LEN) =
                    AZ-TEST-NAME-FOR-SUB(1:AZ-TEST-NAME-LEN)
                 ADD 1 TO AZ-RECORD-COUNT(1)
               ELSE
                 MOVE 1 TO AZ-RECORD-COUNT(1)
                 MOVE AZ-TEST-NAME-FOR-SUB(1:AZ-TEST-NAME-LEN)
                   TO AZ-LAST-TEST-NAME(1:AZ-TEST-NAME-LEN)
                 MOVE AZ-TEST-NAME-LEN
                   TO AZ-LAST-TEST-NAME-LEN
               END-IF
               EVALUATE AZ-TEST-NAME-FOR-SUB(1:AZ-TEST-NAME-LEN)
                 WHEN SPACE
                   CONTINUE
                 WHEN 'TEST2'
                   PERFORM P360-OUTPUT-TEST2
                   PERFORM P360-INPUT-TEST2
                 WHEN OTHER
                   CONTINUE
                 END-EVALUATE
             WHEN 409
               DISPLAY 'EXEC CICS LINK (Statement=409,Line=176)'
             WHEN 423
               DISPLAY 'EXEC CICS LINK (Statement=423,Line=190)'
             WHEN OTHER
               CONTINUE
             END-EVALUATE
           END-IF.
      * EXEC CICS RETURN
           IF ARG0-1 = X'0e08'
             DISPLAY 'EXEC CICS RETURN'
             DISPLAY 'Statement Number:' ARG0-3A-1
             EVALUATE ARG0-3A-1
             WHEN 0
               CONTINUE
             WHEN 367
               DISPLAY 'EXEC CICS RETURN (Statement=367,Line=134)'
             WHEN OTHER
               CONTINUE
             END-EVALUATE
             CALL 'AZUASTPA' USING BY VALUE AZ-TEST-CASE-PTR
           END-IF.
           DISPLAY 'DFHEI1 Successful.'
           GOBACK.
       P360-OUTPUT-TEST2.
           INITIALIZE AZ-COMPARE-WORK-ITEMS
           IF AZ-RECORD-COUNT(1) = 0 THEN
             CONTINUE
           ELSE IF AZ-RECORD-COUNT(1) = 1
             IF LGIPDB01 = ZUT00000000 THEN
               CONTINUE
             ELSE
               MOVE LGIPDB01 TO ZUT0000004B(1)
               MOVE ZUT00000000 TO ZUT0000004B(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT0000004A
               MOVE LENGTH OF ZUT0000004A TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT0000004B(1)
               MOVE 8 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT0000004B(2)
               MOVE 8 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-REQUEST-ID OF DFHCOMMAREA = ZUT00000001 THEN
               CONTINUE
             ELSE
               MOVE CA-REQUEST-ID OF DFHCOMMAREA TO ZUT00000023(1)
               MOVE ZUT00000001 TO ZUT00000023(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000022
               MOVE LENGTH OF ZUT00000022 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000023(1)
               MOVE 6 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000023(2)
               MOVE 6 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF (CA-RETURN-CODE OF DFHCOMMAREA IS NUMERIC)
                 AND (CA-RETURN-CODE OF DFHCOMMAREA = 0) THEN
               CONTINUE
             ELSE
               MOVE CA-RETURN-CODE OF DFHCOMMAREA TO ZUT00000025(1)
               MOVE 0 TO ZUT00000025(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000024
               MOVE LENGTH OF ZUT00000024 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000025(1)
               MOVE 2 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000025(2)
               MOVE 2 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF (CA-CUSTOMER-NUM OF DFHCOMMAREA IS NUMERIC)
                 AND (CA-CUSTOMER-NUM OF DFHCOMMAREA = 2) THEN
               CONTINUE
             ELSE
               MOVE CA-CUSTOMER-NUM OF DFHCOMMAREA TO ZUT00000027(1)
               MOVE 2 TO ZUT00000027(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000026
               MOVE LENGTH OF ZUT00000026 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000027(1)
               MOVE 10 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000027(2)
               MOVE 10 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF (CA-POLICY-NUM OF CA-POLICY-REQUEST OF DFHCOMMAREA IS
           NUMERIC)
                 AND (CA-POLICY-NUM OF CA-POLICY-REQUEST OF
           DFHCOMMAREA = 1) THEN
               CONTINUE
             ELSE
               MOVE CA-POLICY-NUM OF CA-POLICY-REQUEST OF DFHCOMMAREA
           TO ZUT00000029(1)
               MOVE 1 TO ZUT00000029(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000028
               MOVE LENGTH OF ZUT00000028 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000029(1)
               MOVE 10 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000029(2)
               MOVE 10 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-ISSUE-DATE OF CA-POLICY-COMMON OF CA-POLICY-REQUEST
           OF DFHCOMMAREA = ZUT00000002 THEN
               CONTINUE
             ELSE
               MOVE CA-ISSUE-DATE OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA TO ZUT0000002B(1)
               MOVE ZUT00000002 TO ZUT0000002B(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT0000002A
               MOVE LENGTH OF ZUT0000002A TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT0000002B(1)
               MOVE 10 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT0000002B(2)
               MOVE 10 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-EXPIRY-DATE OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA = ZUT00000003 THEN
               CONTINUE
             ELSE
               MOVE CA-EXPIRY-DATE OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA TO ZUT0000002D(1)
               MOVE ZUT00000003 TO ZUT0000002D(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT0000002C
               MOVE LENGTH OF ZUT0000002C TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT0000002D(1)
               MOVE 10 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT0000002D(2)
               MOVE 10 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-LASTCHANGED OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA = ZUT00000004 THEN
               CONTINUE
             ELSE
               MOVE CA-LASTCHANGED OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA TO ZUT0000002F(1)
               MOVE ZUT00000004 TO ZUT0000002F(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT0000002E
               MOVE LENGTH OF ZUT0000002E TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT0000002F(1)
               MOVE 26 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT0000002F(2)
               MOVE 26 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-BROKERID-AZ OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA = ZUT00000005 THEN
               CONTINUE
             ELSE
               PERFORM VARYING AZ-I FROM 1 BY 1 UNTIL AZ-I > 10
                 MOVE CA-BROKERID-AZ OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA(AZ-I:1) TO
           AZ-CONVERT-HEXIN
                 PERFORM CONVERT
                 COMPUTE AZ-J = AZ-I * 2 - 1
                 MOVE AZ-CONVERT-HEXVAL TO ZUT00000031(1)(AZ-J:2)
               END-PERFORM
               PERFORM VARYING AZ-I FROM 1 BY 1 UNTIL AZ-I > 10
                 MOVE ZUT00000005(AZ-I:1) TO AZ-CONVERT-HEXIN
                 PERFORM CONVERT
                 COMPUTE AZ-J = AZ-I * 2 - 1
                 MOVE AZ-CONVERT-HEXVAL TO ZUT00000031(2)(AZ-J:2)
               END-PERFORM
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000030
               MOVE LENGTH OF ZUT00000030 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000031(1)
               MOVE 20 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000031(2)
               MOVE 20 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-BROKERSREF OF CA-POLICY-COMMON OF CA-POLICY-REQUEST
           OF DFHCOMMAREA = ZUT00000006 THEN
               CONTINUE
             ELSE
               MOVE CA-BROKERSREF OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA TO ZUT00000033(1)
               MOVE ZUT00000006 TO ZUT00000033(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000032
               MOVE LENGTH OF ZUT00000032 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000033(1)
               MOVE 10 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000033(2)
               MOVE 10 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-PAYMENT-AZ OF CA-POLICY-COMMON OF CA-POLICY-REQUEST
           OF DFHCOMMAREA = ZUT00000007 THEN
               CONTINUE
             ELSE
               PERFORM VARYING AZ-I FROM 1 BY 1 UNTIL AZ-I > 6
                 MOVE CA-PAYMENT-AZ OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA(AZ-I:1) TO
           AZ-CONVERT-HEXIN
                 PERFORM CONVERT
                 COMPUTE AZ-J = AZ-I * 2 - 1
                 MOVE AZ-CONVERT-HEXVAL TO ZUT00000035(1)(AZ-J:2)
               END-PERFORM
               PERFORM VARYING AZ-I FROM 1 BY 1 UNTIL AZ-I > 6
                 MOVE ZUT00000007(AZ-I:1) TO AZ-CONVERT-HEXIN
                 PERFORM CONVERT
                 COMPUTE AZ-J = AZ-I * 2 - 1
                 MOVE AZ-CONVERT-HEXVAL TO ZUT00000035(2)(AZ-J:2)
               END-PERFORM
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000034
               MOVE LENGTH OF ZUT00000034 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000035(1)
               MOVE 12 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000035(2)
               MOVE 12 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-M-MAKE OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA = ZUT00000008 THEN
               CONTINUE
             ELSE
               MOVE CA-M-MAKE OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA TO ZUT00000037(1)
               MOVE ZUT00000008 TO ZUT00000037(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000036
               MOVE LENGTH OF ZUT00000036 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000037(1)
               MOVE 15 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000037(2)
               MOVE 15 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-M-MODEL OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA = ZUT00000009 THEN
               CONTINUE
             ELSE
               MOVE CA-M-MODEL OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA TO ZUT00000039(1)
               MOVE ZUT00000009 TO ZUT00000039(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000038
               MOVE LENGTH OF ZUT00000038 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000039(1)
               MOVE 15 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000039(2)
               MOVE 15 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-M-VALUE-AZ OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA = ZUT0000000A THEN
               CONTINUE
             ELSE
               PERFORM VARYING AZ-I FROM 1 BY 1 UNTIL AZ-I > 6
                 MOVE CA-M-VALUE-AZ OF CA-MOTOR OF CA-POLICY-REQUEST
           OF DFHCOMMAREA(AZ-I:1) TO AZ-CONVERT-HEXIN
                 PERFORM CONVERT
                 COMPUTE AZ-J = AZ-I * 2 - 1
                 MOVE AZ-CONVERT-HEXVAL TO ZUT0000003B(1)(AZ-J:2)
               END-PERFORM
               PERFORM VARYING AZ-I FROM 1 BY 1 UNTIL AZ-I > 6
                 MOVE ZUT0000000A(AZ-I:1) TO AZ-CONVERT-HEXIN
                 PERFORM CONVERT
                 COMPUTE AZ-J = AZ-I * 2 - 1
                 MOVE AZ-CONVERT-HEXVAL TO ZUT0000003B(2)(AZ-J:2)
               END-PERFORM
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT0000003A
               MOVE LENGTH OF ZUT0000003A TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT0000003B(1)
               MOVE 12 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT0000003B(2)
               MOVE 12 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-M-REGNUMBER OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA = ZUT0000000B THEN
               CONTINUE
             ELSE
               MOVE CA-M-REGNUMBER OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA TO ZUT0000003D(1)
               MOVE ZUT0000000B TO ZUT0000003D(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT0000003C
               MOVE LENGTH OF ZUT0000003C TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT0000003D(1)
               MOVE 7 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT0000003D(2)
               MOVE 7 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-M-COLOUR OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA = ZUT0000000C THEN
               CONTINUE
             ELSE
               MOVE CA-M-COLOUR OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA TO ZUT0000003F(1)
               MOVE ZUT0000000C TO ZUT0000003F(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT0000003E
               MOVE LENGTH OF ZUT0000003E TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT0000003F(1)
               MOVE 8 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT0000003F(2)
               MOVE 8 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-M-CC-AZ OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA = ZUT0000000D THEN
               CONTINUE
             ELSE
               PERFORM VARYING AZ-I FROM 1 BY 1 UNTIL AZ-I > 4
                 MOVE CA-M-CC-AZ OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA(AZ-I:1) TO AZ-CONVERT-HEXIN
                 PERFORM CONVERT
                 COMPUTE AZ-J = AZ-I * 2 - 1
                 MOVE AZ-CONVERT-HEXVAL TO ZUT00000041(1)(AZ-J:2)
               END-PERFORM
               PERFORM VARYING AZ-I FROM 1 BY 1 UNTIL AZ-I > 4
                 MOVE ZUT0000000D(AZ-I:1) TO AZ-CONVERT-HEXIN
                 PERFORM CONVERT
                 COMPUTE AZ-J = AZ-I * 2 - 1
                 MOVE AZ-CONVERT-HEXVAL TO ZUT00000041(2)(AZ-J:2)
               END-PERFORM
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000040
               MOVE LENGTH OF ZUT00000040 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000041(1)
               MOVE 8 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000041(2)
               MOVE 8 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-M-MANUFACTURED OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA = ZUT0000000E THEN
               CONTINUE
             ELSE
               MOVE CA-M-MANUFACTURED OF CA-MOTOR OF CA-POLICY-REQUEST
           OF DFHCOMMAREA TO ZUT00000043(1)
               MOVE ZUT0000000E TO ZUT00000043(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000042
               MOVE LENGTH OF ZUT00000042 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000043(1)
               MOVE 10 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000043(2)
               MOVE 10 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-M-PREMIUM-AZ OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA = ZUT0000000F THEN
               CONTINUE
             ELSE
               PERFORM VARYING AZ-I FROM 1 BY 1 UNTIL AZ-I > 6
                 MOVE CA-M-PREMIUM-AZ OF CA-MOTOR OF CA-POLICY-REQUEST
           OF DFHCOMMAREA(AZ-I:1) TO AZ-CONVERT-HEXIN
                 PERFORM CONVERT
                 COMPUTE AZ-J = AZ-I * 2 - 1
                 MOVE AZ-CONVERT-HEXVAL TO ZUT00000045(1)(AZ-J:2)
               END-PERFORM
               PERFORM VARYING AZ-I FROM 1 BY 1 UNTIL AZ-I > 6
                 MOVE ZUT0000000F(AZ-I:1) TO AZ-CONVERT-HEXIN
                 PERFORM CONVERT
                 COMPUTE AZ-J = AZ-I * 2 - 1
                 MOVE AZ-CONVERT-HEXVAL TO ZUT00000045(2)(AZ-J:2)
               END-PERFORM
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000044
               MOVE LENGTH OF ZUT00000044 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000045(1)
               MOVE 12 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000045(2)
               MOVE 12 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-M-ACCIDENTS-AZ OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA = ZUT00000010 THEN
               CONTINUE
             ELSE
               PERFORM VARYING AZ-I FROM 1 BY 1 UNTIL AZ-I > 6
                 MOVE CA-M-ACCIDENTS-AZ OF CA-MOTOR OF
           CA-POLICY-REQUEST OF DFHCOMMAREA(AZ-I:1) TO
           AZ-CONVERT-HEXIN
                 PERFORM CONVERT
                 COMPUTE AZ-J = AZ-I * 2 - 1
                 MOVE AZ-CONVERT-HEXVAL TO ZUT00000047(1)(AZ-J:2)
               END-PERFORM
               PERFORM VARYING AZ-I FROM 1 BY 1 UNTIL AZ-I > 6
                 MOVE ZUT00000010(AZ-I:1) TO AZ-CONVERT-HEXIN
                 PERFORM CONVERT
                 COMPUTE AZ-J = AZ-I * 2 - 1
                 MOVE AZ-CONVERT-HEXVAL TO ZUT00000047(2)(AZ-J:2)
               END-PERFORM
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000046
               MOVE LENGTH OF ZUT00000046 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000047(1)
               MOVE 12 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000047(2)
               MOVE 12 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
             IF CA-M-FILLER OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA = ZUT00000011 THEN
               CONTINUE
             ELSE
               MOVE CA-M-FILLER OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA TO ZUT00000049(1)
               MOVE ZUT00000011 TO ZUT00000049(2)
               SET AZ-COMPARE-ITEM-NAME-PTR TO ADDRESS OF ZUT00000048
               MOVE LENGTH OF ZUT00000048 TO AZ-COMPARE-ITEM-NAME-LEN
               SET AZ-COMPARE-ITEM-VALUE-PTR TO ADDRESS OF
           ZUT00000049(1)
               MOVE 32323 TO AZ-COMPARE-ITEM-VALUE-LEN
               SET AZ-COMPARE-ITEM-EXP-VALUE-PTR TO ADDRESS OF
           ZUT00000049(2)
               MOVE 32323 TO AZ-COMPARE-ITEM-EXP-VALUE-LEN
               MOVE 1 TO FAIL-MESSAGE-LEN
               STRING
                 'Compare failed at record 1 '
                 'in EXEC CICS LINK (line=127).'
                 DELIMITED BY SIZE INTO FAIL-MESSAGE-TXT
                 WITH POINTER FAIL-MESSAGE-LEN
               END-STRING
               SUBTRACT 1 FROM FAIL-MESSAGE-LEN
               PERFORM THROW-ASSERTION
             END-IF
           ELSE
             CONTINUE
               END-IF
           END-IF.
       P360-INPUT-TEST2.
           IF AZ-RECORD-COUNT(1) = 0 THEN
             CONTINUE
           ELSE IF AZ-RECORD-COUNT(1) = 1
             MOVE ZUT00000012 TO CA-REQUEST-ID OF DFHCOMMAREA
             MOVE 0 TO CA-RETURN-CODE OF DFHCOMMAREA
             MOVE 2 TO CA-CUSTOMER-NUM OF DFHCOMMAREA
             MOVE 1 TO CA-POLICY-NUM OF CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE ZUT00000013 TO CA-ISSUE-DATE OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE ZUT00000014 TO CA-EXPIRY-DATE OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE ZUT00000015 TO CA-LASTCHANGED OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE 0 TO CA-BROKERID OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE ZUT00000016 TO CA-BROKERSREF OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE 0 TO CA-PAYMENT OF CA-POLICY-COMMON OF
           CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE ZUT00000017 TO CA-M-MAKE OF CA-MOTOR OF
           CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE ZUT00000018 TO CA-M-MODEL OF CA-MOTOR OF
           CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE 8500 TO CA-M-VALUE OF CA-MOTOR OF CA-POLICY-REQUEST
           OF DFHCOMMAREA
             MOVE ZUT00000019 TO CA-M-REGNUMBER OF CA-MOTOR OF
           CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE ZUT0000001A TO CA-M-COLOUR OF CA-MOTOR OF
           CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE 1000 TO CA-M-CC OF CA-MOTOR OF CA-POLICY-REQUEST OF
           DFHCOMMAREA
             MOVE ZUT0000001B TO CA-M-MANUFACTURED OF CA-MOTOR OF
           CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE 450 TO CA-M-PREMIUM OF CA-MOTOR OF CA-POLICY-REQUEST
           OF DFHCOMMAREA
             MOVE 0 TO CA-M-ACCIDENTS OF CA-MOTOR OF CA-POLICY-REQUEST
           OF DFHCOMMAREA
             MOVE ZUT0000001C TO CA-M-FILLER OF CA-MOTOR OF
           CA-POLICY-REQUEST OF DFHCOMMAREA
             MOVE 94853 TO EIBTIME OF DFHEIBLK
             MOVE 119037 TO EIBDATE OF DFHEIBLK
             MOVE ZUT0000001D TO EIBTRNID OF DFHEIBLK
             MOVE 394 TO EIBTASKN OF DFHEIBLK
             MOVE ZUT0000001E TO EIBTRMID OF DFHEIBLK
             MOVE 0 TO DFHEIGDI OF DFHEIBLK
             MOVE 1848 TO EIBCPOSN OF DFHEIBLK
             MOVE 32500 TO EIBCALEN OF DFHEIBLK
             MOVE ZUT0000001F TO EIBAID OF DFHEIBLK
             MOVE ZUT00000020 TO EIBFN-AZ OF DFHEIBLK
             MOVE ZUT00000021 TO EIBRSRCE OF DFHEIBLK
             MOVE 0 TO EIBRESP OF DFHEIBLK
             MOVE 0 TO EIBRESP2 OF DFHEIBLK
           ELSE
             CONTINUE
           END-IF
           END-IF.
       CONVERT.
           MOVE AZ-CONVERT-HEXIN TO AZ-DECBYTE
           DIVIDE AZ-DEC BY 16 GIVING AZ-Q REMAINDER AZ-R
           COMPUTE AZ-Q1 = AZ-Q + 1
           COMPUTE AZ-R1 = AZ-R + 1
           MOVE AZ-HEXSTR(AZ-Q1:1) TO AZ-CONVERT-HEXVAL(1:1)
           MOVE AZ-HEXSTR(AZ-R1:1) TO AZ-CONVERT-HEXVAL(2:1)
           EXIT.
       THROW-ASSERTION.
      *    throw an assertion exception (ends test)
           CALL 'AZUASTFC' USING BY VALUE AZ-TEST-CASE-PTR
                   BY REFERENCE FAIL-MESSAGE-TXT
                   BY VALUE FAIL-MESSAGE-LEN
                   BY VALUE AZ-COMPARE-ITEM-NAME-PTR
                   BY VALUE AZ-COMPARE-ITEM-NAME-LEN
                   BY VALUE AZ-COMPARE-ITEM-VALUE-PTR
                   BY VALUE AZ-COMPARE-ITEM-VALUE-LEN
                   BY VALUE AZ-COMPARE-ITEM-EXP-VALUE-PTR
                   BY VALUE AZ-COMPARE-ITEM-EXP-VALUE-LEN
           EXIT.
       END PROGRAM DFHEI1.